### ISSUE TITLE
issue with import command

### ISSUE THREAD

**Issue by stan789** [CS2103AUG2017-W15-B3/main#101]
if the file only contains for .vcf file, 
![screen shot 2017-11-03 at 3 14 55 pm](https://user-images.githubusercontent.com/31248689/32363331-d433f112-c0a9-11e7-9e04-d7b1e20af9ac.png)

BEGIN:VCARD
VERSION:4.0
N:Johnny;Ive;;;
FN:Johnny Ive
END:VCARD

for VCard, no error thrown or success to tell user.

**Comment by limshunyong** [comment]
Hi @stan789,

Thank you reporting this issue to us. An improvement has been made to the error handling and it should resolve the issue you had reported.
Thanks and good luck to your project demo =)

Shunyong
