### ISSUE TITLE
code quality comments for JasmineSee

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W15-B3/main#120]
![image](https://user-images.githubusercontent.com/1023494/32652213-8e8b79f6-c63e-11e7-9bef-cfa50bd96d83.png)
- `Deletes ...` is a better way of wording it

@JasmineSee  FYA

**Comment by JasmineSee** [comment]
Hi @okkhoy ,
Thanks for the review. I have changed the code according to your comment.
