### ISSUE TITLE
code quality comments for limshunyong

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W15-B3/main#123]
![image](https://user-images.githubusercontent.com/1023494/32652545-910365ee-c63f-11e7-8491-b1b58cd1a8b6.png)
- better would be `Exports ...`

@limshunyong fya

**Comment by limshunyong** [comment]
Hi @okkhoy, thanks for the review.
I have changed the comments based on what you have mentioned in #132 .
