### ISSUE TITLE
As a user I want to upload images to different contacts

### ISSUE THREAD

**Issue by JasmineSee** [CS2103AUG2017-W15-B3/main#35]

**Comment by JasmineSee** [comment]
so that i can easily identify them.

**Comment by blaqkrow** [comment]
@JasmineSee are you uploading directly from the computer? shall I assist you in the GUI aspect? like displaying the Pictures in the personList?

**Comment by JasmineSee** [comment]
@blaqkrow Yes. I'm thinking of either typing upload or clicking on a button to open the file explorer. Sure, that will help me a lot! Thank you!

**Comment by blaqkrow** [comment]
Both would work! If you manage to code a command for it i can wrap it with an upload button! shall discuss this tmr!
