### ISSUE TITLE
"qrcall 2" doesn't work

### ISSUE THREAD

**Issue by LimeHeap** [CS2103AUG2017-W15-B3/main#99]
the browser window changes to map instead of expected qr code

**Comment by LimeHeap** [comment]
![qrcall2](https://user-images.githubusercontent.com/28524249/32363222-2a1ad6a0-c0a9-11e7-97c3-948db9a0d6d4.png)

**Comment by LimeFallacie** [comment]
update: "qr 5" also opens to map, but the address is wrong

**Comment by danielweide** [comment]
Hi Lime , would like to know what process you did to trigger that issue ? On my end i did several testing and does not encounter your issue

**Comment by LimeHeap** [comment]
on my terminal; when i type "qrcall 2" directly onto the CLI, the map appeared instead

**Comment by danielweide** [comment]
I think i have fixed that already . The newer version or edited code should work well.
